port: 19374
debug_port: 53202
root_path: ares-root
total_memory_size: 161061273600 # 150gb
query:
  device_memory_utilization: 0.95
  device_choosing_timeout: 10
  # enable timezone column for queries with "timezone": "timezone(city_id)"
  timezone_table:
    table_name: api_cities
disk_store:
  write_sync: true
meta_store:
  write_sync: true
http:
  max_connections: 300
  read_time_out_in_seconds: 20
  write_time_out_in_seconds: 300 # 5 minutes to write the result

clients:
  # example controller client configs
  controller:
    host: localhost
    port: 6708
    headers:
      RPC-Caller:
        - aresdb
      RPC-Service:
        - ares-controller

cluster:
  enable: false
  cluster_name: ""

